### ISSUE TITLE
Конфигурация для Travis-CI

### ISSUE THREAD

**Issue by drsgdev** [UNN-CS/mp2-lab5-poly#6]
Предлагаю добавлять в конфигурацию для тревиса версию дистрибутива `Xenial(Ubuntu 16.04)` для запуска, т.к. там более новые компиляторы, которые поддерживают новые версии языка и библиотеки(например, `<regex>`).
`.travis.yml:`
```yml
os: linux
dist: xenial
дальше основная конфигурация
```
